version: 3.8'

services:
  minio:
    image: 'minio/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINI_ROOT_USER: root
      MINI_ROOT_PASSWORD: 123456
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
volumes:
  minio_data: {}
